server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7002/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.bjfs.fsjy.springcloud.service.PaymentFeignService: debug
